### ISSUE TITLE
Custom fields

### ISSUE THREAD

**Issue by leadingproperties** [teachbase/amorail#7]
Hi.
Sorry to trouble you, but have an issue with custom fields, that not clear for me. 

So from you guide I understand that I need to add custom fields   in secrets.yaml.

> "AmoCRM is using "custom_fields" architecture, to get all information for your account, you can find properties and set up configuration manually in config/secrets.yml."

I make a lot of attempts with no luck.
In final I got this secrets yaml:

```
amorail:
      usermail: 'myusername'
      api_key: 'mytoken'
      api_endpoint: 'myAMOdomain'
      custom_fields:
        contacts:
          -
            id: "1628873"
            name: "user_hash"
            code: ""
            multiple: "N"
            type_id: "1"
            disabled: "0"
          -
            id: "1634385"
            name: "lp_db_id"
            code: ""
            multiple: "N"
            type_id: "2"
            disabled: "0"
```

And still have problems with as example get Contact.
1. Contact "test@t.com" have custom field **lp_db_id**  and empty **user_hash**
 result:

```
Amorail::Contact.find_by_query("test@t.com")
=> [#<Amorail::Contact:0x007fc019f909a8 @last_modified=1435166323, @id=65601902, @name="test", @date_create=1435166279, @responsible_user_id=271104, @company_name="", @linked_company_id="0", @email="test@t.com">]
```

So we got Contact but without **lp_db_id**
1. Contact "test@t.com" have custom field **lp_db_id**  and **user_hash**
   result:

```
Amorail::Contact.find_by_query("test@t.com")
=> key not found: "code"
```

In this case we got an error.

What I'm doing wrong? Thinks that may be something not good in yaml file. 
Thanks.
